name:                kademlia-haskell
version:             0.1.0.0
github:              "o1labs/kademlia-haskell"
license:             MIT
author:              "Brandon Kase"
maintainer:          "bkase@o1labs.org"
copyright:           "2018 O(1) Labs"

extra-source-files:
- ChangeLog.md
- README.md

dependencies:
- base                >= 4.7 && < 5
- base64-bytestring   >= 1.0.0.1
- binary              >= 0.8.3
- bytestring          >= 0.10.2 && < 0.11
- containers          >= 0.5.5.1
- data-default        >= 0.7
- extra               >= 1.4
- kademlia            >= 1.1.0.1
- MonadRandom
- hashable            >= 1.2.5.0
- mtl                 >= 2.1.3.1
- network             >= 2.8 && < 2.9
- random
- random-shuffle
- transformers        >= 0.3
- transformers-compat >= 0.3.3
- unix                >= 2.7.2.1

executables:
  kademlia:
    main:             Main.hs
    source-dirs:      app
    ghc-options:
    - -Wall
    - -fno-warn-orphans
    - -O2
    default-extensions:
    - DeriveDataTypeable
    - DeriveGeneric
    - GeneralizedNewtypeDeriving
    - OverloadedStrings
    - RecordWildCards
    - TypeApplications
