resolver: lts-9.21
packages:
- '.'
nix:
  enable: false
  packages: [gmp]
extra-deps:
- git: https://github.com/bkase/kademlia.git
  commit: 7120bb4d28e708acd52dfd61d3dca7914fac7d7f
flags: {}
extra-package-dbs: []
